import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const conversationId = "clf89cejf0000une8gtu3lu9z"; // test conversation useQuery by Id
  const questionText = "Mi pregunta bro";
  const questionId = "clf89uxxx0000unegzh2j9j4g"; // test question useQuery by Id

  // test conversation useQuery by Id

  const conversationResponse = api.conversation.getConversation.useQuery(
    {
      conversationId,
    },
    {
      enabled: !!conversationId,
    }
  );

  const conversation = conversationResponse.data;
  console.log(conversation, "conversation");

  // test question useQuery by Id

  const questionResponse = api.question.getQuestion.useQuery(
    {
      questionId,
    },
    {
      enabled: !!questionId,
    }
  );

  const question = questionResponse.data;
  console.log(question, "question");

  // test question submit

  const submitQuestion = api.question.submitQuestion.useMutation();

  const handleQuestion = () => {
    submitQuestion.mutateAsync({
      conversationId,
      questionText,
    });
    console.log("submitted", conversationId, questionText);
  };

  return (
    <>
      <Head>
        <title>Get the conversation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {conversationResponse.isLoading ? (
          <>Loading...</>
        ) : (
          <>
            {conversation?.answers.map((answer) => {
              <p key={answer.id}>{answer.text}</p>;
            })}
            {conversation?.questions.map((question) => {
              <p key={question.id}>{question.text}</p>;
            })}
          </>
        )}
        <button onClick={handleQuestion}>Mandar texto</button>
      </div>
    </>
  );
};

export default Home;
